### ISSUE TITLE
Hello !

### ISSUE THREAD

**Issue by Okimi-** [baptistecdr/ThymioKit#1]
Bonjour !
Je suis le créateur/développeur de l'application Blockly4Thymio : 
[Okimi-/Blockly4Thymio-Compilateur](https://github.com/Okimi-/Blockly4Thymio-Compilateur)

Je découvre à l'instant votre projet ThymioKit, pouvez-vous m'en dire plus à propos de ce projet, ce qu'il permet de faire avec Thymio et comment ?

**Comment by baptistecdr** [comment]
Bonjour,
Merci de votre commentaire ça me fait extrêmement plaisir !
Ma librairie permet de contrôler le robot Thymio via une application C#. On peut mettre en marche les moteurs, allumer les LEDs, jouer des sons qui sont dans le Thymio, jouer une fréquence. On peut même gérer les événements des capteurs de proximité. La création de petit script Thymio est donc  faisable via ma librairie.
Voici un exemple qui permet de jouer un son quand un capteur de proximité détecte un objet :
`Thymio t = new Thymio();
t.Sensors[0].OnDetect(Operator.LessThan, 100,  t.Sound.ToString(SoundType.Fearful));
t.Execute();
`
Les actions sont stockées dans une liste de string, puis je construis un fichier AESL et je l'envoie via asebahttp (j'ai d'ailleurs repris votre méthode d'envoie que je n'ai pas encore commit).

PS: Merci d'avoir signalé le bug d'envoi avec asebahttp car je commençais à m'arracher les cheveux en voyant ce message d'erreur ! 
Si vous d'autres questions n'hésitez pas.
